[project]
authors = ["Reflekt Team"]
entry = "main.sw"
license = "MIT"
name = "reflekt_token"

[dependencies]
std = { git = "https://github.com/fuellabs/sway", tag = "v0.49.3" }

[contract-dependencies]
